### GET
GET http://localhost:5001/

### GET Vehicles
GET http://localhost:5001/api/vehicles

### GET specific vehicle
GET http://localhost:5001/api/vehicles/2

### Query string
GET http://localhost:5001/api/query?search=For

### POST request
POST http://localhost:5001/api/vehicles
Content-Type: application/json

{
    "make" :"Opel"
}

### PUT
PUT http://localhost:5001/api/vehicles/2
Content-Type: application/json

{
    "make" : "Volvo"
}

### PUT fail
PUT http://localhost:5001/api/vehicles/4
Content-Type: application/json

{
    "make" : "Volvo"
}

### Delete
DELETE http://localhost:5001/api/vehicles/3


### Delete fail
DELETE http://localhost:5001/api/vehicles/4